// Custom worker entrypoint: wraps the OpenNext-generated handler (fetch for the
// Next.js app) and adds the queue consumer and cron handlers that Next.js
// itself has no surface for. `.open-next/worker.js` exists after
// `opennextjs-cloudflare build`.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- generated by `opennextjs-cloudflare build`; absent before the first build
import openNextHandler from "./.open-next/worker.js";

import { handleGenerationBatch } from "./src/queue/consumer";
import { handleScheduled } from "./src/cron";
import type { GenerationMessage } from "./src/queue/messages";

export default {
  fetch: openNextHandler.fetch,

  async queue(batch: MessageBatch<GenerationMessage>, env: CloudflareEnv, ctx: ExecutionContext) {
    await handleGenerationBatch(batch, env, ctx);
  },

  async scheduled(controller: ScheduledController, env: CloudflareEnv, ctx: ExecutionContext) {
    await handleScheduled(controller, env, ctx);
  },
} satisfies ExportedHandler<CloudflareEnv, GenerationMessage>;
