import { hasLocale } from "next-intl";
import { routing } from "@/i18n/routing";
import { getFeedPage } from "@/lib/public/queries";
import { getPublicContext } from "@/lib/public/site";

const escapeXml = (text: string) =>
  text
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ locale: string }> },
): Promise<Response> {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) return new Response("Not found", { status: 404 });

  const { db, settings, origin } = await getPublicContext();
  const { articles } = await getFeedPage(
    { db, locale, primaryLocale: settings.default_locale },
    1,
  );

  const items = articles
    .map((a) => {
      const url = `${origin}/${locale}/articles/${a.slug}`;
      return `    <item>
      <title>${escapeXml(a.title)}</title>
      <link>${url}</link>
      <guid isPermaLink="false">taradiddle-article-${a.id}</guid>
      <description>${escapeXml(a.summary)}</description>
      <category>${escapeXml(a.category.name)}</category>
      <pubDate>${a.generatedAt.toUTCString()}</pubDate>
    </item>`;
    })
    .join("\n");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Taradiddle.news${locale === "pl" ? " (PL)" : ""}</title>
    <link>${origin}/${locale}</link>
    <atom:link href="${origin}/${locale}/feed.xml" rel="self" type="application/rss+xml"/>
    <description>A fully automated satirical publication. Every article is fiction generated by a language model.</description>
    <language>${locale}</language>
${items}
  </channel>
</rss>`;

  return new Response(xml, {
    headers: {
      "content-type": "application/rss+xml; charset=utf-8",
      "cache-control": "public, max-age=900",
    },
  });
}
