/**
 * Generates drizzle/seed.sql from the canonical defaults. Idempotent
 * (INSERT OR IGNORE everywhere), so it is safe to re-run.
 *
 * Run: npm run db:seed:build
 * Apply: npm run db:seed:local | db:seed:remote
 */
import { writeFileSync } from "node:fs";
import { DEFAULT_PROFILE, DEFAULT_SETTINGS, STARTER_CATEGORIES } from "./defaults.ts";

const q = (value: string) => `'${value.replaceAll("'", "''")}'`;

const lines: string[] = [
  "-- Generated by src/db/build-seed.ts — do not edit by hand.",
  "",
];

for (const [key, value] of Object.entries(DEFAULT_SETTINGS)) {
  lines.push(
    `INSERT OR IGNORE INTO settings (key, value) VALUES (${q(key)}, ${q(JSON.stringify(value))});`,
  );
}
lines.push("");

lines.push(
  `INSERT OR IGNORE INTO generation_profiles (name, model, temperature, max_output_tokens, instructions, is_default)` +
    ` VALUES (${q(DEFAULT_PROFILE.name)}, ${q(DEFAULT_PROFILE.model)}, NULL, ${DEFAULT_PROFILE.maxOutputTokens}, ${q(DEFAULT_PROFILE.instructions)}, 1);`,
);
lines.push("");

STARTER_CATEGORIES.forEach((category, i) => {
  const id = i + 1;
  lines.push(`INSERT OR IGNORE INTO categories (id) VALUES (${id});`);
  for (const locale of ["en", "pl"] as const) {
    const { name, slug } = category[locale];
    lines.push(
      `INSERT OR IGNORE INTO category_translations (category_id, locale, name, slug)` +
        ` VALUES (${id}, ${q(locale)}, ${q(name)}, ${q(slug)});`,
    );
  }
});
lines.push("");

// Lives outside ./drizzle on purpose: that directory is wrangler's
// migrations_dir, and anything in it would be applied (once) as a migration.
writeFileSync(new URL("../../seed.sql", import.meta.url), lines.join("\n"));
console.log("seed.sql written");
